# site settings
title: Ski
subtitle: With Perrine
email: youremailaddress@gmail.com
description: Discover the joy of skiing with Perrine.
description_fr: Découvrez le plaisir de skier avec Perrine.
baseurl: "" # the subpath of your site, e.g. /blog
url: "skiwithperrine.com"
form_url: https://docs.google.com/forms/d/e/formResponse
author: Perrine
resorts:
  - name: Saint Gervais les Bains
    url: https://www.saintgervais.com
  - name: Les Contamines
    url: https://www.lescontamines.com
  - name: Megeve
    url: https://www.megeve-tourisme.fr
  - name: Chamonix Mont-Blanc
    url: https://www.chamonix.com

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub:
  GitLab:
  Google-Plus:
  Instagram: https://www.instagram.com/skiwithperrine
  LinkedIn:
  Twitter:
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
  - "*.gemspec"
  - LICENSE.md
  - CONTRIBUTING.md
  - README.md
